version: '3.8'

services:

  postgres:
    image: postgres:15.6 # latest # 16.1 
    container_name: flask_postgres
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASWOR_DB}
      POSTGRES_DB: flask_database
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - flask_postgres_data:/var/lib/postgresql/data
    networks:
      - flask-network


volumes:
  flask_postgres_data:

networks:
  flask-network:
    driver: bridge

